"""Use LRO_TRANS_REF

Revision ID: 05ad0a9154f6
Revises: 54adb0b171aa
Create Date: 2016-02-17 16:31:20.532222

"""

# revision identifiers, used by Alembic.
revision = '05ad0a9154f6'
down_revision = '54adb0b171aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_search_and_results', sa.Column('lro_trans_ref', sa.String(length=30), nullable=True))
    op.create_index('idx_title_number', 'user_search_and_results', ['title_number'], unique=False)
    op.drop_column('user_search_and_results', 'transaction_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_search_and_results', sa.Column('transaction_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index('idx_title_number', table_name='user_search_and_results')
    op.drop_column('user_search_and_results', 'lro_trans_ref')
    ### end Alembic commands ###
