"""Add UPRN mapping table

Revision ID: 18124bf31811
Revises: 45a35ac9bfe
Create Date: 2016-02-10 16:56:27.823515

"""

# revision identifiers, used by Alembic.
revision = '18124bf31811'
down_revision = '45a35ac9bfe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uprn_mapping',
    sa.Column('uprn', sa.String(length=20), nullable=False),
    sa.Column('lr_uprn', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('uprn')
    )
    op.alter_column('title_register_data', 'lr_uprns',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('title_register_data', 'lr_uprns',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_table('uprn_mapping')
    ### end Alembic commands ###

