"""Add official copy data column

Revision ID: 2bbd8de7dcb
Revises: 59cbcf04663
Create Date: 2015-06-29 11:08:37.905618

"""

# revision identifiers, used by Alembic.
revision = '2bbd8de7dcb'
down_revision = '59cbcf04663'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_register_data', sa.Column('official_copy_data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title_register_data', 'official_copy_data')
    ### end Alembic commands ###
