"""Add UPRN mapping table

Revision ID: 36316acef1a
Revises: 45a35ac9bfe
Create Date: 2015-09-22 16:36:26.390621

"""

# revision identifiers, used by Alembic.
revision = '36316acef1a'
down_revision = '45a35ac9bfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uprn_mapping',
    sa.Column('uprn', sa.String(length=20), nullable=False),
    sa.Column('lr_uprn', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('uprn')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uprn_mapping')
    ### end Alembic commands ###