"""Add lr_uprns column

Revision ID: 51df6986a47
Revises: 2bbd8de7dcb
Create Date: 2015-09-18 14:17:02.373005

"""

# revision identifiers, used by Alembic.
revision = '51df6986a47'
down_revision = '2bbd8de7dcb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_register_data', sa.Column('lr_uprns', postgresql.ARRAY(sa.String()), nullable=False))
    op.create_index('idx_title_uprns', 'title_register_data', ['lr_uprns'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_title_uprns', table_name='title_register_data')
    op.drop_column('title_register_data', 'lr_uprns')
    ### end Alembic commands ###
