"""restrict-summary-access

Revision ID: 54adb0b171aa
Revises: 36316acef1a
Create Date: 2016-02-15 12:16:23.365067

"""

# revision identifiers, used by Alembic.
revision = '54adb0b171aa'
down_revision = '36316acef1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_and_results',
    sa.Column('lro_trans_ref', sa.String(length=30), nullable=True),
    sa.Column('search_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('title_number', sa.String(length=20), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.String(length=10), nullable=False),
    sa.Column('cart_id', sa.String(length=30), nullable=True),
    sa.Column('viewed_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('search_datetime', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_search_and_results')
    ### end Alembic commands ###
