"""Initial migration

Revision ID: 59935c933ab
Revises: None
Create Date: 2015-04-10 10:16:12.530777

"""

# revision identifiers, used by Alembic.
revision = '59935c933ab'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_register_data',
    sa.Column('title_number', sa.String(length=10), nullable=False),
    sa.Column('register_data', postgresql.JSON(), nullable=True),
    sa.Column('geometry_data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('title_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_register_data')
    ### end Alembic commands ###
