"""Restrict summary access

Revision ID: 73b223519cdb
Revises: 36316acef1a
Create Date: 2016-03-03 10:38:09.877599

"""

# revision identifiers, used by Alembic.
revision = '73b223519cdb'
down_revision = '36316acef1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_search_and_results',
    sa.Column('search_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('title_number', sa.String(length=20), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.String(length=10), nullable=False),
    sa.Column('cart_id', sa.String(length=30), nullable=True),
    sa.Column('lro_trans_ref', sa.String(length=30), nullable=True),
    sa.Column('viewed_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid', sa.Boolean, default=False),
    sa.PrimaryKeyConstraint('search_datetime', 'user_id')
    )
    op.create_index('idx_title_number', 'user_search_and_results', ['title_number'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_title_number', table_name='user_search_and_results')
    op.drop_table('user_search_and_results')
    ### end Alembic commands ###
