"""Add Title Summary View table

Revision ID: d4badafdbb4b
Revises: 18124bf31811
Create Date: 2016-02-10 16:57:42.037507

"""

# revision identifiers, used by Alembic.
revision = 'd4badafdbb4b'
down_revision = '18124bf31811'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_summary_view',
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('title_number', sa.String(length=20), nullable=False),
    sa.Column('viewed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_summary_view')
    ### end Alembic commands ###
